/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BorrowedBookResponse } from '../../models/borrowed-book-response';

export interface ReturnBorrowedBook$Params {
  bookUuid: string;
}

export function returnBorrowedBook(http: HttpClient, rootUrl: string, params: ReturnBorrowedBook$Params, context?: HttpContext): Observable<StrictHttpResponse<BorrowedBookResponse>> {
  const rb = new RequestBuilder(rootUrl, returnBorrowedBook.PATH, 'patch');
  if (params) {
    rb.path('bookUuid', params.bookUuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BorrowedBookResponse>;
    })
  );
}

returnBorrowedBook.PATH = '/books/borrow/return/{bookUuid}';
