/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedBackResponse } from '../models/feed-back-response';
export interface PageResponseFeedBackResponse {
  first?: boolean;
  hydraMember?: Array<FeedBackResponse>;
  hydraTotal?: number;
  last?: boolean;
  page?: number;
  size?: number;
  totalPages?: number;
}
